### ISSUE TITLE
Vacuum process fails if a table in the configuration file does not exist

### ISSUE THREAD

**Issue by jmnunezizu** [HotelsDotCom/housekeeping#29]
In the scenario where the vacuum tool is executed with a configuration file that contains tables A, B, and C and table C does not exist; the tool fails.

Unfortunately, it fails half-way through the vacuum process, which is quite annoying.

Ideally, it should perform any of the following options:

a. Validate all tables in the configuration file before the execution begins, and exit if one of them is missing; or
b. Print a warning when it tries to vacuum the non-existent table, and then issue a summary towards the end of the execution with the results.

I'd prefer option b.

Regards,
–Jose

**Comment by massdosage** [comment]
FWIW, option (b) would be more in line with how Circus Train works and we could do something like it does which then has return codes as described here: https://github.com/HotelsDotCom/circus-train/#exit-codes (replace the word "replications" with "housekeeping runs". We can probably even base the code required here on it.

**Comment by jmnunezizu** [comment]
Adding return codes to option (b) is a bonus and a good idea. Good call.

**Comment by patduin** [comment]
I've added explicit validation which as a side effect affects this issue: see PR https://github.com/HotelsDotCom/housekeeping/pull/39
So from a user if you specify a non existent table. The validation will fail (all tables are validated) and you are prompted to fix your config. None of the vacuum will run.
I am a bit concerned if we just report a failure in the logs and continue it will never be found and subsequent return codes will probably ignore as well as it looks like it is running. imo better to fail fast and make sure the config is correct before running.
thoughts?

**Comment by jmnunezizu** [comment]
When I raised the issue, I said I preferred option b. Actually, I prefer option a, as I completely agree with you that failing fast is better. No need to wait until the end and check any return codes and see what happened with the run.

**Comment by massdosage** [comment]
The current validation does this table check as an implicit side-effect, if you turned the table validation off then it wouldn't catch this. My suggestion is we do this:

* We have the boolean to control table validation and we clearly state in the documentation that it does two things - (1) checks that each table exists, (2) checks that the table contains the properties. If a user just wants the "does table exist" check they can set the value for the properties to "".
* When the validation occurs it first checks if the table exists - if not then it logs a message saying the table doesn't exist (as opposed to the message saying that the property doesn't exist). 

This way the user can control whether they want to do just a "table existence" check (boolean is true, property is empty string), or a "table property check" (boolean is true, property is default or some string)  or do no checks at all (set the boolean to false).

**Comment by patduin** [comment]
no, it will always check if the tables exist even if you list no properties to check

We don't have a boolean to control or turn on the table validation it is alway on.

**Comment by massdosage** [comment]
OK, so you always get (1) then. That's fine. And if you want that but don't want to check any properties what do you do? Provide a list with one empty string?

**Comment by patduin** [comment]
you can overwrite with:
```
tables-validation:
  hive-table-properties:
```

**Comment by patduin** [comment]
fixed in PR #39
