### ISSUE TITLE
Documentation missing for expired-path-duration

### ISSUE THREAD

**Issue by jmnunezizu** [HotelsDotCom/housekeeping#31]
Hi,

The configuration option `expired-path-duration` that's used in https://github.com/HotelsDotCom/housekeeping/blob/master/housekeeping/src/test/java/com/hotels/housekeeping/conf/HousekeepingIntegrationTest.java#L57 seems to be missing from the `README.md`.

It's present in the Circus Train `README.md` here: https://github.com/HotelsDotCom/circus-train#configuring-housekeeping. 

It should also be added in the `README.md` of the Housekeeping Tool given that it's the place where most users will check.

Regards,
–Jose

**Comment by massdosage** [comment]
One possibility would be to *move* the documentation from CT (https://github.com/HotelsDotCom/circus-train#configuring-housekeeping) to this project instead and then just provide a link from CT to here.

**Comment by jmnunezizu** [comment]
I think it's a good idea. Housekeeping started as part of CT but then left the suburbs and moved to the city :)
